QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Controllers/QLDGController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLiThuVien.Models;
using Limilabs.Barcode;
using System.Web.Helpers;
using System.Drawing;
using System.Web.UI.DataVisualization;
using System.Web.UI.DataVisualization.Charting;
using System.IO;
using System.Net.Mail;
using System.Net;



namespace QuanLiThuVien.Controllers
{
    public class QLDGController : Controller
    {
        //
        // GET: /QLDG/

        public static QLThuVienEntities4 ql;
        public ActionResult main()
        {
            ql = new QLThuVienEntities4();
            return View();
        }
        [HttpPost]
        public PartialViewResult PhatSinh()
        {
            //QLThuVienEntities1 ql = new QLThuVienEntities1();
            List<tbl_DocGia_Tam> lst = (from e in ql.tbl_DocGia_Tam select e).ToList();
            return PartialView("PhatSinh", lst);
        }
        public bool MoveImage(string dg, string newDG) {
            bool kq = true;
            try
            {
                string path1 = Server.MapPath("~/Content/images/docGiaTam");
                string[] Files = Directory.GetFiles(path1, dg + ".*")
                                         .Select(path => Path.GetFileName(path))
                                         .ToArray();
                
                string path2 = Server.MapPath("~/Content/images/docgia");
                Image t = Image.FromFile(path1 + "/" + Files[0]); //.Save(path2 + "/" + Files[0].Split('.')[0].ToLower() + ".png", System.Drawing.Imaging.ImageFormat.Png);
                t.Save(path2 + "/" + newDG + ".png", System.Drawing.Imaging.ImageFormat.Png);
                t.Dispose();
                FileInfo file = new FileInfo(path1 + "/" + Files[0]);
                file.Delete();
            }
            catch (Exception ex)
            {
                kq = false;
            }
            return kq;
        }
        public tbl_DocGia GanDocGia(string masothe, tbl_DocGia_Tam dg)  //gan doc gia tam (tbl_DocGiaTam) vao bang doc gia chinh (tbl_DocGia)
        {
            tbl_DocGia docgiamoi = new tbl_DocGia();
            docgiamoi.ID = masothe;
            docgiamoi.Ten = dg.Ten;
            docgiamoi.DiaChi = dg.DiaChi;
            docgiamoi.Email = dg.Email;
            docgiamoi.SDT = dg.SDT;
            docgiamoi.CMND = dg.CMND;
            docgiamoi.MSSV = dg.MSSV;
            docgiamoi.Khoa = dg.Khoa;
            docgiamoi.NgaySinh = dg.NgaySinh;
            docgiamoi.GioiTinh = dg.GioiTinh;
            docgiamoi.NgayCapNhat = dg.NgayCapNhat;
            docgiamoi.NgayHetHan = dg.NgayHetHan;
            docgiamoi.User = "n";
            docgiamoi.Pass = "n";
            return docgiamoi;
        }
        public string PhatSinhTenHinhAnh(QLThuVienEntities4 ql)         //phat sinh ten hinh anh cho anh doc gia trong bang chinh
        {
            string masothe = "";
            var stt = (from e in ql.tbl_DocGia select e.CMND);
            string head = stt.Count().ToString();
            int soluongkitu = stt.Count().ToString().Length;
            for (int i = 0; i < (4 - soluongkitu); i++)
            {
                head = "0" + head;
            }

            string end = DateTime.Now.ToString().Trim();
            end = end.Substring(0, 4);
            //dinh nghia ma so the
            masothe = end + head;
            return masothe;
        }
        [HttpPost]
        public PartialViewResult Barcode_MaSoThe()  //t va t.id phai cung ten voi Jquery trong PhatSinh.cshtml
        { 
            int id =int.Parse( RouteData.Values["id"].ToString());
            //QLThuVienEntities1 ql = new QLThuVienEntities1();
            tbl_DocGia_Tam dg = (from e in ql.tbl_DocGia_Tam
                                where e.ID == id
                                select
                                e
                                ).First();
            string masothe = PhatSinhTenHinhAnh(ql);                //phat sinh ten hinh anh / ma cua doc gia moi
            tbl_DocGia docgiamoi = GanDocGia(masothe, dg);
            ql.tbl_DocGia.Add(docgiamoi);
            ql.SaveChanges();

            //*************gui mail cho doc gia xac nhan la da duoc them moi thanh cong
            var client = new SmtpClient("smtp.gmail.com", 587)
            {
                Credentials = new NetworkCredential("lamtrongnhan0505@gmail.com", "tieu diet"),
                EnableSsl = true
            };
            string title = "Thu vien Dai Hoc Khoa Hoc Tu Nhien";
            string body = "chao " + docgiamoi.Ten + "; \n Ban da duoc tro thanh thanh vien cua thu vien: \n Username: " + docgiamoi.User + "\n Password: " + docgiamoi.Pass + "\n Xin cam on";
            client.Send("lamtrongnhan0505@gmail.com", docgiamoi.Email.ToString(), title, body);
            //************

            //*********** phat sinh barcode cho doc gia
            BaseBarcode barcode = BarcodeFactory.GetBarcode(Symbology.Code11);
            barcode.Number = masothe;
            barcode.ChecksumAdd = true;
            string path = Server.MapPath(@"~\Content\images\barcode\" + masothe + ".gif");   //luu barcode vua tao
            barcode.Save(path, ImageType.Gif);
            //************

            if (!MoveImage(dg.ID.ToString(), masothe))
            {
                return PartialView("Error");
            }

            //*************xoa doc gia vua tao trong bang tbl_DocGiaTam
            ql.tbl_DocGia_Tam.Remove(dg);
            ql.SaveChanges();
            //************
            
            //************ load lai trang web
            return PhatSinh();  
        }
        
        public PartialViewResult TK_DG_Khoa()
        {       
            var data = from dg in ql.tbl_DocGia
                       group dg by dg.Khoa into m
                       select new { tong = m.Count(), ten = m.Key };
            List<DocGia_TK> dg1 = new List<DocGia_TK>();
            System.Web.UI.DataVisualization.Charting.Chart Chart2 = new System.Web.UI.DataVisualization.Charting.Chart();
           
            Chart2.Width = 500;
            Chart2.Height = 400;
            Chart2.ChartAreas.Add("thong ke khoa").BackColor = System.Drawing.Color.FromArgb(64, System.Drawing.Color.White);

            Chart2.Palette = ChartColorPalette.EarthTones;
            Chart2.Titles.Add("THỐNG KÊ THEO KHOA");
            Series series = Chart2.Series.Add("thong ke");
            Chart2.Series.Clear();
            Chart2.Series.Add(series);
            Chart2.Series[0].ChartType = SeriesChartType.Pie;
            
            int tongSo = 0;
            foreach (var tam in data)
            {
                DocGia_TK tt = new DocGia_TK();
                tt.ten = tam.ten;
                tt.tong = tam.tong;
                dg1.Add(tt);
                tongSo += tam.tong;
                series.Points.AddXY(tam.ten, tam.tong);
            }
            ViewBag.tongSo = tongSo.ToString();
            Chart2.BackColor = Color.Transparent;
            //MemoryStream imageStream = new MemoryStream();
            string nam = DateTime.Now.ToString().Trim();
            nam = nam.Substring(0, 4)+nam.Substring(4,3);
            string path = Server.MapPath(@"~\Content\images\ThongKeKhoa" + nam+".png" );
            Chart2.SaveImage(path, ChartImageFormat.Png);
            //Chart2.TextAntiAliasingQuality = TextAntiAliasingQuality.SystemDefault;
            //Response.ContentType = "image/png";
            ViewBag.link = @"../Content/images/ThongKeKhoa" + nam + ".png";  //path.Replace('\\', '/');         
            return PartialView("TK_DG_Khoa", dg1);
        }
        public PartialViewResult TK_DG_Nam()
        {    
            List<DocGia_TK> dd = new List<DocGia_TK>();
            var data = from dg in ql.tbl_DocGia
                       group dg by dg.NgayCapNhat.Value.Year into m
                       select new { tong = m.Count(), ten = m.Key };
            System.Web.UI.DataVisualization.Charting.Chart Chart2 = new System.Web.UI.DataVisualization.Charting.Chart();

            Chart2.Width = 500;
            Chart2.Height = 400;
            Chart2.ChartAreas.Add("thong ke nam").BackColor = System.Drawing.Color.FromArgb(64, System.Drawing.Color.White);

            Chart2.Palette = ChartColorPalette.Chocolate;
            Chart2.Titles.Add("THÔNG KÊ THEO NĂM");
            Series series = Chart2.Series.Add("thong ke");
            Chart2.Series.Clear();
            Chart2.Series.Add(series);
            Chart2.Series[0].ChartType = SeriesChartType.Line;
            int tongSo = 0;
            foreach (var tam in data)
            {
                tongSo += tam.tong;
                DocGia_TK h = new DocGia_TK();
                h.ten = tam.ten.ToString();
                h.tong = tam.tong;
                dd.Add(h);
                series.Points.AddXY(tam.ten, tam.tong);
            }
            ViewBag.tongSo = tongSo.ToString();
            Chart2.BackColor = Color.White;
            //MemoryStream imageStream = new MemoryStream();
            string nam = DateTime.Now.ToString().Trim();
            nam = nam.Substring(0, 4) + nam.Substring(4, 3);
            string path = Server.MapPath(@"~\Content\images\ThongKeNam" + nam + ".png");
            Chart2.SaveImage(path, ChartImageFormat.Png);
            //Chart2.TextAntiAliasingQuality = TextAntiAliasingQuality.SystemDefault;
            //Response.ContentType = "image/png";
            ViewBag.linkNam = @"../Content/images/ThongKeNam" + nam + ".png";  //path.Replace('\\', '/');         
            return PartialView("TK_DG_Nam", dd);
        }
        public PartialViewResult DS_DocGia()
        {
            //QLThuVienEntities1 ql = new QLThuVienEntities1();
            List<tbl_DocGia> t = (from e in ql.tbl_DocGia select e ).ToList();
            return PartialView("View_DSDocGia",t);
        }
        /*public ActionResult Mail()
        {

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/QLDG/InThe.cshtml
@model QuanLiThuVien.Models.tbl_DocGia

@{
    //ViewBag.Title = "InThe";
}

<html>
    <head>
        <title>In the doc gia</title>
    </head>
    <body style="height:230px; width:300px; background-color: #b3faa5; border:black solid 1px;">
        <table border="0">
            
            
                <tr>
                    <td>
                        <img width="150" height="120" src="@Url.Content("~/content/images/docgia/"+Model.ID +".png" )" />
                    </td>
                    <td>
                        <ul>
                            <li style="text-align:center;"> THE THU VIEN</li>
                            <li>Ho ten: @Model.Ten</li>
                            <li>Gioi tinh: @Model.GioiTinh</li>
                            <li>Dia chi: @Model.DiaChi</li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center;">
                        <img width="150" height="80" src="@Url.Content("~/content/images/barcode/"+Model.ID+".gif" )" />
                    </td>
                </tr>
                
            
        </table>
    </body>
</html>

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/QLDG/PhatSinh.cshtml
@model IEnumerable<QuanLiThuVien.Models.tbl_DocGia_Tam>
    <h2>PhatSinh Barcode Ma So The</h2>
<script type="text/javascript">
   /* $(document).ready(function () {
        $("#btn_PhatSinh").on("click", function () {
            var t = { id: $(this).siblings("#id1").val() };
            var kt = true;
            $.ajax({
                type: "POST",
                url: "/home/Barcode_MaSoThe",
                data: t,
                success: function () {
                    alert("da them thanh cong");
                    //$(this).parent().parent().remove();
                    //location.reload();
                },
                error: function () {
                    kt = false;
                    alert("co loi");
                }
            });
            if (kt) {
                //alert("ok");
                $(this).parent().parent().remove();
            }
        });
    });*/
</script>
@if(Model!=null)
{
    <table border="1" style="background-color: white;" >
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SDT)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Khoa)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.NgayCapNhat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayHetHan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pass)
            </th>
            <th>--||--</th>

            
        </tr>
        
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SDT)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Khoa)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.NgayCapNhat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayHetHan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pass)
                </td>
                <td>
                    <input type="hidden" value="@item.ID.ToString()" id="id1" />
                    @Ajax.ActionLink("Phat sinh","Barcode_MaSoThe","QLDG",
                                        new RouteValueDictionary{{"id",@item.ID.ToString()}} ,
                                        new AjaxOptions
                                        {
                                            HttpMethod="POST",
                                            InsertionMode=InsertionMode.Replace,
                                            UpdateTargetId= "content_phai",
                                            OnBegin= "Hide",
                                            OnComplete="Show",
                                            LoadingElementId="loading"
                                        })
                </td>                
            </tr>
        }
        
    </table>
}else{
    <span>khong co du lieu</span>
}
<script type="text/javascript">
    function Hide()
    {
        $("#content_phai").hide();
    }
    function Show()
    {
        $("#content_phai").show();
    }
</script>

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/QLDG/TK_DG_Khoa.cshtml
@model IEnumerable<QuanLiThuVien.Models.DocGia_TK>
@{
    ViewBag.Title = "TK_DG_Khoa";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="text-align:center;"> Thống Kê Đọc Giả Theo Khoa</h2>
    <div style="float:left;">
        <img src="@ViewBag.link" />
    </div>
    <div style="float:left; padding: 2%;">
        <table id="tk_dg_khoa">
            <tr>
                <th>Khoa</th>
                <th>tong so</th>
                <th>phan tram</th>
            </tr>
            @foreach (var tam in Model)
            {
                <tr>
                    <td>@tam.ten</td>
                    <td>@tam.tong</td>
                    <td>@(((double)tam.tong/int.Parse(ViewBag.tongSo))*100)</td>
                </tr>
            }
        </table>
    </div>


    

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/QLDG/TK_DG_Nam.cshtml
@model IEnumerable<QuanLiThuVien.Models.DocGia_TK>

@{
    ViewBag.Title = "TK_DG_Nam";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center;">Thống Kê Đọc Giả Theo Năm</h2>

    <div style="float:left;">
        <img src="@ViewBag.linkNam" />
    </div>
    <div style="float:left; padding: 2%;">
        <table id="tk_dg_nam">
            <tr>
                <th>Nam</th>
                <th>tong so</th>
                <th>phan tram</th>
            </tr>
            @foreach (var tam in Model)
            {
                <tr>
                    <td>@tam.ten</td>
                    <td>@tam.tong</td>
                    <td>@(((double)tam.tong/int.Parse(ViewBag.tongSo))*100)</td>
                </tr>
            }
        </table>
    </div>

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/QLDG/View_DSDocGia.cshtml
@model IEnumerable<QuanLiThuVien.Models.tbl_DocGia>

@{
    ViewBag.Title = "View_DSDocGia";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            padding: 5px;
            text-align: left;
        }
    </style>
-->
<script type="text/javascript">
    $(document).ready(function () {
        // setup the dialog
        /*$("#the").dialog({
            modal: true,
            autoOpen: false,
            height: 100,
            width: 200
        });*/
       
        // bind the click event
        /*$("#ClickMe").on("click", function (event) {
            alert("ok");
            event.preventDefault();
            
            $(this).after().first().dialog("open");  // show dialog
        });*/
    });
</script>

    <table style="width:100%">
        <caption>Thông Tin Đọc Giả</caption>
        <tr>
            <th>Hinh Anh</th>
            <th>Ten</th>
            <th>Dia Chi</th>
            <th>Email</th>
            <th>SDT</th>
            <th>Khoa</th>
            <th>Ngay Cap Nhat</th>
            <th> Ngay Het Han</th>
            <th> User</th>
            <th> Pass</th>
            <th></th>
        </tr>

        @foreach(var item in Model)
        {
            
            <tr>
                <td>
                    <img width="150" height="120" src="@Url.Content("~/content/images/docgia/"+@item.ID+".png" )" />     
                </td>
                <td>@item.Ten</td>
                <td>@item.DiaChi</td>
                <td>@item.Email</td>
                <td>@item.SDT</td>
                <td>@item.Khoa</td>
                <td>@item.NgayCapNhat</td>
                <td>@item.NgayHetHan</td>
                <td>
                   
                    <input type="hidden" value="@item.ID" id="idCard" />
                    <input type="button" name="@item.ID" onclick="PopUpCard(this.name.toString());" Value="In"  />
                </td>
            </tr>
            
        }
    </table>

<script type="text/javascript">
    function PopUpCard(t)   //chua truyen duoc bien t
    {
        //alert(t);
        var id = new String();
        id = t;
        window.showModalDialog("/QLDG/InThe?id="+id, id, "dialogHeight:250px; dialogWidth:320px;");
        
    }
</script>

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/QLDG/main.cshtml
@{
    ViewBag.Title = "main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>quan ly doc gia</h2>
<div id="content_trai">
    <ul>
        <li>@Ajax.ActionLink("Phát Sinh Barcode","PhatSinh","QLDG",new AjaxOptions{
        HttpMethod="POST",
        InsertionMode= InsertionMode.Replace,
        UpdateTargetId="content_phai"})
                          
        </li>
        <li>@Ajax.ActionLink("Thống Kê Theo Khoa","TK_DG_Khoa","QLDG",new AjaxOptions{
        HttpMethod="POST",
        InsertionMode= InsertionMode.Replace,
        UpdateTargetId="content_phai"})</li>
        <li>
            @Ajax.ActionLink("Thống Kê Theo Năm","TK_DG_Nam","QLDG",new AjaxOptions{
                HttpMethod="POST",
                InsertionMode= InsertionMode.Replace,
                UpdateTargetId="content_phai"})               
        </li>
        <li>@Ajax.ActionLink("Danh sach doc gia","DS_DocGia","QLDG",new AjaxOptions{
                HttpMethod="POST",
                InsertionMode= InsertionMode.Replace,
                UpdateTargetId="content_phai"}) 

        </li>
    </ul>
</div>
<div id="content_phai">
    <h2>trang danh cho Nhan Vien quan ly doc gia</h2>
   
</div>
<div id="loading" style="display: none;">
    loading...
</div>