QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Controllers/HoTroDocGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using QuanLiThuVien.Models;
using System.Web.Mvc;

namespace QuanLiThuVien.Controllers
{
    public class HoTroDocGiaController : Controller
    {
     
        //
        // GET: /HoTroDocGia/
        public static QLThuVienEntities4 data;
        public ActionResult main()
        {
            data = new QLThuVienEntities4();
            return View();
        }
        public ActionResult XemThongtinmuon()
        {
            string tt = Session["username"].ToString().Trim();
            var result = (from p in data.phieumuons
                         where p.tbl_DocGia.ID == tt & p.Ngaytra==null //Where data.Docgias.ID=data.phieumuon.IDdocgia and data.Docgias.username=getSession(sender,e)
                         select p);
            return View(result);
        }
        public ActionResult giahan(int id)
        {

            if (id >= 0)
            {
                //QuanlyEntities23 data = new QuanlyEntities2(); 
                data.sp_Giahan(id);//Goi procedure Gia han sach trong SQLserver
                data.SaveChanges();
                data = new QLThuVienEntities4();
                //return RedirectToAction("XemThongtinmuon","Home");
            }
            
            string tt = Session["username"].ToString().Trim();
            var result = (from p in data.phieumuons
                          where p.tbl_DocGia.ID == tt & p.Ngaytra == null //Where data.Docgias.ID=data.phieumuon.IDdocgia and data.Docgias.username=getSession(sender,e)
                          select p);
            return View(result);
        }
    }
}

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/HoTroDocGia/XemThongtinmuon.cshtml
@model IEnumerable<QuanLiThuVien.Models.phieumuon>


<table style=" border-collapse:collapse" cellpadding="5px" border="1">
    <tr>
        <th>
            Tên sách
        </th>
        
        <th>
            Tác Giả
        </th>
        <th>
            Nhà Xuất Bản
        </th>
        <th>
            Ngày mượn
        </th>
        <th>
            Ngày hết hạn
        </th>
        <th>
            Số lần gia hạn
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Sach.Tensach)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Sach.Tacgia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sach.Namsx)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngaymuon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngayhethan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolanGH)
            </td>
            <td>

                @Html.ActionLink("Gia Hạn", "giahan",
            new { id = item.IDsach }, new { onclick = "return confirm('Ban muon gia han sach nay ?')" })
            </td>
        </tr>
    }

</table>

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/HoTroDocGia/giahan.cshtml
@model IEnumerable<QuanLiThuVien.Models.phieumuon>



@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}


    <table style=" border-collapse:collapse" cellpadding="5px" border="1">
        <tr>
            <th>
                Tên sách
            </th>
            <th>
                ID sách
            </th>
            <th>
                Ngày mượn
            </th>
            <th>
                Ngày hết hạn
            </th>
            <th>
                Số lần gia hạn
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Sach.Tensach)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.IDsach)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ngaymuon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ngayhethan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SolanGH)
                </td>
                <td>

                    @Ajax.ActionLink("Gia Hạn", "giahan", "HoTroDocGia",
                    new { id = item.IDsach }, new AjaxOptions
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "content_phai"
                    })
                </td>
            </tr>
        }

    </table>

QuanLiThuVien_KhoaHocTuNhien_nhom1/QuanLiThuVien/Views/HoTroDocGia/main.cshtml
@{
    ViewBag.Title = "main";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>quan ly doc gia</h2>
<div id="content_trai">
    <ul>
        
   
<li>
    @Ajax.ActionLink("Xemthongtinmuon", "giahan", "HoTroDocGia",new {id="-1"}, new AjaxOptions
       {
           HttpMethod = "POST",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "content_phai"
       })

</li>
</ul>
</div>
<div id="content_phai">
    <h2>trang danh cho  doc gia</h2>

</div>
<div id="loading" style="display: none;">
    loading...
</div>